name: Checks
on:
  push:
    branches:
      - main
  pull_request: {}
  workflow_dispatch: {}
jobs:
  checks:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - uses: pre-commit/action@v3.0.1
