on:
    push:
      branches:
        - main

jobs:
    documentation:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-python@v5
            with:
              python-version: 3.11
          - name: Install
            run: |
              python -m pip install -U pip
              pip install --progress-bar off .
              pip install --progress-bar off ".[docs]"
          - name: Build
            run: |
              cd docs
              make html
              cd ..
          - name: Deploy
            uses: peaceiris/actions-gh-pages@v3
            with:
              github_token: ${{ secrets.GITHUB_TOKEN }}
              publish_dir: ./docs/_build/html
