name: Checks
on:
  push:
    branches:
      - main
  pull_request: {}
  workflow_dispatch: {}
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Install
      run: |
        python -m pip install --upgrade pip
        pip install --progress-bar off -U setuptools
        pip install --progress-bar off .
        pip install --progress-bar off .[test]
    - name: Run Test
      run: pytest tests
